export default {
    registering: "Registering...",
    ooops: "Ooops...",
    badLogin: "Cannot login! Please check your email address or password!",
    welcome: "Welcome",
    congratulations: "Congratulations",
    welcomeMessage: "Hi {0}. Your registration is complete. A confirmation link was sent to {1}. Please confirm before login",
    continue: "Continue",
    register: "Register",
    forgotPassword: "Forgot password",
    signIn: "Sign in",
    mailAddress: "Mail Address",
    name: "Name",
    password: "Password",
    accountConfirmText: "Please insert your email address to recover password. We will send a new password in your mailbox!",
    accountConfirmed: "Your account is confirmed. You can login now",
    cannotLogin: "Cannot login",
    mailAndPasswordRequired: "Email and password are required",
    cannotRegister: "Cannot register",
    nameMailAndPasswordRequired: "Name, email and password are required",
    cannotConfirmAccount: "Cannot confirm account",
    activationCodeRequired: "Activation code required",
}
