export default {
    registering: "Registering...",
    ooops: "Ooops...",
    badLogin: "Cannot login! Please check your email address or password!",
    welcome: "Welcome",
    congratulations: "Congratulations",
    welcomeMessage: "Hi {0}, your registration is complete.\nA confirmation link was sent to {1}.\nPlease confirm before login",
    continue: "Continue",
    register: "Register",
    forgotPassword: "Forgot password",
    signIn: "Sign in",
    mailAddress: "Mail Address",
    name: "Name",
    password: "Password",
    accountConfirmText: "Insert activation code that we sent to your mailbox to confirm your account",
    accountConfirmed: "Your account is confirmed. You can login now",
    mailAndPasswordRequired: "Email and password are required",
    nameMailAndPasswordRequired: "Name, email and password are required",
    mailRequired: "Email is required",
    activationCodeRequired: "Activation code required",
    accountRecoverText: "Please insert your email address to recover password. We will send a new password in your mailbox!",
    problemOccoured: "There is a problem",
    accountRecovered: "A new password was sent to {0}",
    pleaseSpecifyId: "Please specify an ID",
    pleaseSpecifyQuery: "Please specify a query",
    pleaseSpecifyEntity: "Please specify the entity",
    search: "Search",
    close: "Close",
    selectFilterType: "Select filter type",
    typeValueToSearch: "Type value to search",
    value: "Value",
    filters: "Filters",
    pagination: "Showing {0} to {1} of {2}",
    noResults: "there are no results with the specified criteria",
    selectAll: "Select all",
    delete: "Delete",
    create: "Create",
    refresh: "Refresh",
    confirm: "Confirm",
    entityDeleteConfirm: "Are you sure to delete {0} entities?",
    submit: "Submit",
    cancel: "Cancel"
}
