"use strict"

export const LOGIN = "LOGIN";
export const RESUME_SESSION = "RESUME_SESSION"
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const RECOVER_ACCOUNT = "RECOVER_ACCOUNT"
export const SET_ACTIVATION_CODE = "SET_ACTIVATION_CODE"
export const CONFIRM_ACCOUNT = "CONFIRM_ACCOUNT"

export const GET_GRID = "GET_GRID"
export const LOAD_ENTITIES = "LOAD_ENTITIES"
export const DELETE_ENTITIES = "DELETE_ENTITIES"
export const SAVE_ENTITY = "SAVE_ENTITY"
export const NEW_ENTITY = "NEW_ENTITY"
export const GET_ENTITY = "GET_ENTITY"
export const FREE_ENTITIES = "FREE_ENTITIES"
export const GET_LOOKUP_RESULT = "GET_LOOKUP_RESULT"
export const GET_LOOKUP_VALUES = "GET_LOOKUP_VALUES"
export const FREE_LOOKUP = "FREE_LOOKUP"
export const GET_SELECT_ENTITIES = "GET_SELECT_ENTITIES"
export const GET_SELECT_VALUES = "GET_SELECT_VALUES"
export const FREE_SELECT = "FREE_SELECT"

export const SETUP_MENU = "SETUP_MENU"
export const SET_ACTIVE_MENU_ITEM = "SET_ACTIVE_MENU_ITEM"
export const EXPAND_MENU_ITEM = "EXPAND_MENU_ITEM"

export const GET_USER_COVER_IMAGE = "GET_USER_COVER_IMAGE"
export const GET_USER_PROFILE_IMAGE = "GET_USER_PROFILE_IMAGE"

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";