
//
//  Actions.swift
//
//  Auto generated from aj build
//

import Foundation
        
struct Actions {
	static let LOGIN = "LOGIN"
	static let LOGIN_COMPLETE = "LOGIN_COMPLETE"
	static let LOGIN_ERROR = "LOGIN_ERROR"
	static let RESUME_SESSION = "RESUME_SESSION"
	static let RESUME_SESSION_COMPLETE = "RESUME_SESSION_COMPLETE"
	static let RESUME_SESSION_ERROR = "RESUME_SESSION_ERROR"
	static let LOGOUT = "LOGOUT"
	static let REGISTER = "REGISTER"
	static let REGISTRATION_COMPLETE = "REGISTRATION_COMPLETE"
	static let REGISTRATION_ERROR = "REGISTRATION_ERROR"
	static let RECOVER_ACCOUNT = "RECOVER_ACCOUNT"
	static let RECOVER_ACCOUNT_COMPLETE = "RECOVER_ACCOUNT_COMPLETE"
	static let RECOVER_ACCOUNT_ERROR = "RECOVER_ACCOUNT_ERROR"
	static let SET_ACTIVATION_CODE = "SET_ACTIVATION_CODE"
	static let CONFIRM_ACCOUNT = "CONFIRM_ACCOUNT"
	static let CONFIRM_ACCOUNT_COMPLETE = "CONFIRM_ACCOUNT_COMPLETE"
	static let CONFIRM_ACCOUNT_ERROR = "CONFIRM_ACCOUNT_ERROR"
}
