#!/bin/bash

FRAMEWORK_VERSION="2.3.1"

if [ -z "$JAVA_HOME" ]; then
    echo "Please set JAVA_HOME"
    exit 1
fi

if [ -z "$APPLICAFRAMEWORK_HOME" ]; then
  SOURCE="${BASH_SOURCE[0]}"
  while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  done
  APPLICAFRAMEWORK_HOME="$( cd -P "$( dirname "$SOURCE" )"; cd .. >/dev/null 2>&1 && pwd )"
fi

JAVA="$JAVA_HOME/bin/java"
JAR="${APPLICAFRAMEWORK_HOME}/scripts/target/scripts-$FRAMEWORK_VERSION.jar"
"$JAVA" -cp "${APPLICAFRAMEWORK_HOME}/scripts/target/lib/*:$JAR" applica.framework.Applica $@

