#!/bin/bash

FRAMEWORK_VERSION="2.3.0.1"

if [ -z "$JAVA_HOME" ]; then
    echo "Please set JAVA_HOME"
    exit
fi

JAVA="$JAVA_HOME/bin/java"
JAR="${APPLICAFRAMEWORK_HOME}/scripts/target/scripts-$FRAMEWORK_VERSION.jar"
"$JAVA" -cp "${APPLICAFRAMEWORK_HOME}/scripts/target/lib/*:$JAR" applica.framework.Applica $@

